In [8]:
%run microbe2.py
import pandas as pd 
from io import StringIO

fn = '201208_dh5a_growth_curve.csv'
df, g = readPlates(fn)
display(df)
print(g)

,t,C17.0,C17.1,C17.2,C18.3,C18.4,C18.5,C5.6,C5.7,C5.8,...,S6.98,S13.99,S13.100,S13.101,S7.102,S7.103,S7.104,S9.105,S9.106,S9.107
0,0.0,0.091638,0.097108,0.089995,0.082598,0.084995,0.081428,0.071959,0.067861,0.071296,...,0.085743,0.080549,0.084489,0.079135,0.082222,0.082402,0.084277,0.083816,0.082725,0.091482
1,90.0,0.093527,0.099909,0.094283,0.085372,0.087701,0.084588,0.081908,0.078098,0.081932,...,0.090755,0.084620,0.087522,0.083116,0.085547,0.087276,0.087848,0.088546,0.087226,0.098040
2,180.0,0.102339,0.106732,0.100887,0.092899,0.095603,0.093007,0.105597,0.102576,0.107350,...,0.100350,0.095676,0.097963,0.094367,0.097549,0.099233,0.098611,0.099920,0.098188,0.111682
3,270.0,0.113780,0.118258,0.112899,0.104509,0.107645,0.105651,0.135967,0.135709,0.140713,...,0.114185,0.111791,0.113615,0.110610,0.115286,0.116165,0.117333,0.116168,0.112774,0.127155
4,360.0,0.141508,0.144394,0.151309,0.132529,0.136437,0.137759,0.185847,0.185953,0.194759,...,0.143729,0.144512,0.146527,0.145254,0.152056,0.152061,0.154078,0.153502,0.148346,0.159674
5,1260.0,0.393773,0.401710,0.398006,0.373460,0.384588,0.395315,0.371294,0.377199,0.385568,...,0.355456,0.375111,0.371663,0.392746,0.419215,0.418455,0.417638,0.434519,0.419960,0.443070

{'C17': ['C17.0', 'C17.1', 'C17.2'], 'C18': ['C18.3', 'C18.4', 'C18.5'], 'C5': ['C5.6', 'C5.7', 'C5.8'], 'C6': ['C6.9', 'C6.10', 'C6.11'], 'C16': ['C16.12', 'C16.13', 'C16.14'], 'C13': ['C13.15', 'C13.16', 'C13.17'], 'C8': ['C8.18', 'C8.19', 'C8.20'], 'C7': ['C7.21', 'C7.22', 'C7.23'], 'C12': ['C12.24', 'C12.25', 'C12.26'], 'C4': ['C4.27', 'C4.28', 'C4.29'], 'C19': ['C19.30', 'C19.31', 'C19.32'], 'C1': ['C1.33', 'C1.34', 'C1.35'], 'C3': ['C3.36', 'C3.37', 'C3.38'], 'C9': ['C9.39', 'C9.40', 'C9.41'], 'C14': ['C14.42', 'C14.43', 'C14.44'], 'C11': ['C11.45', 'C11.46', 'C11.47'], 'C2': ['C2.48', 'C2.49', 'C2.50'], 'C10': ['C10.51', 'C10.52', 'C10.53'], 'C15': ['C15.54', 'C15.55', 'C15.56'], 'C20': ['C20.57', 'C20.58', 'C20.59'], 'C21': ['C21.60', 'C21.61', 'C21.62'], 'S3': ['S3.63', 'S3.64', 'S3.65'], 'S4': ['S4.66', 'S4.67', 'S4.68'], 'S2': ['S2.69', 'S2.70', 'S2.71'], 'S14': ['S14.72', 'S14.73', 'S14.74'], 'S10': ['S10.75', 'S10.76', 'S10.77'], 'S5': ['S5.78', 'S5.79', 'S5.80'], 'S12': ['S12.81', 'S12.82', 'S12.83'], 'S8': ['S8.84', 'S8.85', 'S8.86'], 'S1': ['S1.87', 'S1.88', 'S1.89'], 'S11': ['S11.90', 'S11.91', 'S11.92'], 'S15': ['S15.93', 'S15.94', 'S15.95'], 'S6': ['S6.96', 'S6.97', 'S6.98'], 'S13': ['S13.99', 'S13.100', 'S13.101'], 'S7': ['S7.102', 'S7.103', 'S7.104'], 'S9': ['S9.105', 'S9.106', 'S9.107']}

In [12]:
%run microbe2.py

d = growthAnalysis(df, g, 'dh5a')

C17
C18
C5
C6
C16
C13
C8
C7
C12
C4
C19
C1
C3
C9
C14
C11
C2
C10
C15
C20
C21
S3
S4
S2
S14
S10
S5
S12
S8
S1
S11
S15
S6
S13
S7
S9

In [13]:
d

,sample,growth plateau min,growth plateau max,mean growth plateau,std growth plateau,min peak growth rate t,max peak growth rate t,mean peak growth rate t,std peak growth rate t,min shortest doubling time,max shortest doubling time,mean shortest doubling time,std shortest doubling time
0,C17,0.393522,0.401580,0.397651,0.003293,378.787879,393.939394,383.838384,7.142493e+00,108.776902,125.559447,115.662352,7.174769
1,C18,0.373165,0.394958,0.384161,0.008898,378.787879,378.787879,378.787879,0.000000e+00,110.805660,111.951023,111.339899,0.470742
2,C5,0.377321,0.392798,0.384567,0.006357,212.121212,227.272727,217.171717,7.142493e+00,177.222637,186.785894,181.594578,3.946940
3,C6,0.471034,0.483777,0.475915,0.005613,348.484848,348.484848,348.484848,0.000000e+00,144.271105,145.862320,145.221098,0.685321
4,C16,0.228667,0.240442,0.235215,0.004897,424.242424,424.242424,424.242424,0.000000e+00,88.121331,110.721185,103.007609,10.528504
5,C13,0.253625,0.279603,0.263225,0.011638,348.484848,363.636364,353.535354,7.142493e+00,154.430029,177.668973,169.177654,10.467988
6,C8,0.407726,0.420649,0.413561,0.005350,409.090909,409.090909,409.090909,5.684342e-14,73.320281,75.641385,74.602732,0.963140
7,C7,0.221298,0.227335,0.224737,0.002535,393.939394,409.090909,398.989899,7.142493e+00,112.136475,128.492475,118.675770,7.068038
8,C12,0.292358,0.302454,0.297928,0.004187,424.242424,424.242424,424.242424,0.000000e+00,72.458462,79.267721,76.641573,2.989939
9,C4,0.307859,0.312456,0.309407,0.002156,409.090909,409.090909,409.090909,5.684342e-14,88.208713,93.692295,91.294889,2.291029
10,C19,0.391549,0.402922,0.397145,0.004645,363.636364,378.787879,373.737374,7.142493e+00,118.206077,125.805446,121.260636,3.276506
11,C1,0.189170,0.205227,0.195622,0.006924,424.242424,424.242424,424.242424,0.000000e+00,61.493245,72.497204,66.073245,4.677743
12,C3,0.256561,0.266201,0.260864,0.004003,393.939394,393.939394,393.939394,0.000000e+00,100.363305,104.124470,102.616677,1.623475
13,C9,0.310119,0.331754,0.319679,0.009010,363.636364,378.787879,373.737374,7.142493e+00,120.450060,124.977735,123.116371,1.934066
14,C14,0.453728,0.466600,0.459977,0.005262,409.090909,409.090909,409.090909,5.684342e-14,77.023149,81.279964,79.024619,1.747085
15,C11,0.181457,0.191852,0.187625,0.004460,424.242424,424.242424,424.242424,0.000000e+00,80.647027,91.946066,86.949600,4.704360
16,C2,0.473835,0.533626,0.504416,0.024428,287.878788,303.030303,297.979798,7.142493e+00,167.666310,190.730175,175.847152,10.541186
17,C10,0.380650,0.405549,0.390179,0.010972,393.939394,409.090909,404.040404,7.142493e+00,93.156774,98.510912,96.488294,2.373691
18,C15,0.241550,0.249720,0.246621,0.003615,424.242424,424.242424,424.242424,0.000000e+00,77.520292,82.852496,80.662274,2.278521
19,C20,0.360634,0.390236,0.375264,0.012088,378.787879,378.787879,378.787879,0.000000e+00,111.910825,124.416813,118.112144,5.106071
20,C21,0.392994,0.407918,0.400520,0.006093,378.787879,378.787879,378.787879,0.000000e+00,118.370482,125.505622,121.173002,3.107353
21,S3,0.403787,0.438053,0.422321,0.014129,333.333333,333.333333,333.333333,0.000000e+00,155.265313,161.440656,157.843259,2.622108
22,S4,0.287550,0.300497,0.294243,0.005295,409.090909,409.090909,409.090909,5.684342e-14,89.099218,99.781925,94.258473,4.368794
23,S2,0.395598,0.411125,0.403167,0.006345,393.939394,409.090909,398.989899,7.142493e+00,95.004117,101.513191,98.249628,2.657349
24,S14,0.378960,0.397279,0.385877,0.008123,378.787879,378.787879,378.787879,0.000000e+00,114.081917,119.404800,117.297991,2.310285
25,S10,0.326990,0.344309,0.337771,0.007680,378.787879,378.787879,378.787879,0.000000e+00,126.850177,136.803896,130.961791,4.243825
26,S5,0.359773,0.376216,0.369975,0.007274,378.787879,378.787879,378.787879,0.000000e+00,116.358306,124.388489,120.927183,3.370558
27,S12,0.362596,0.376234,0.371030,0.006018,378.787879,378.787879,378.787879,0.000000e+00,122.997689,130.086330,127.084255,2.993805
28,S8,0.372761,0.375214,0.373902,0.001008,409.090909,409.090909,409.090909,5.684342e-14,81.750668,84.209948,82.651590,1.106400
29,S1,0.252244,0.261241,0.257493,0.003823,348.484848,363.636364,358.585859,7.142493e+00,172.222916,180.310845,177.152770,3.531577
30,S11,0.373343,0.387703,0.381296,0.005963,378.787879,378.787879,378.787879,0.000000e+00,121.249925,122.436343,121.984172,0.523814
31,S15,0.379683,0.387498,0.383255,0.003226,363.636364,378.787879,368.686869,7.142493e+00,119.219615,134.515885,128.884684,6.865277
32,S6,0.355044,0.372112,0.365338,0.007399,363.636364,363.636364,363.636364,5.684342e-14,132.861989,144.335841,136.995249,5.204328
33,S13,0.371242,0.392336,0.379402,0.009249,363.636364,363.636364,363.636364,5.684342e-14,125.573497,139.797434,133.709269,5.984682
34,S7,0.417151,0.418753,0.417955,0.000654,363.636364,363.636364,363.636364,5.684342e-14,122.082055,125.717599,123.347750,1.677033
35,S9,0.419590,0.442459,0.432018,0.009441,363.636364,378.787879,368.686869,7.142493e+00,114.827301,119.333244,116.820507,1.875867

In [18]:
d.to_csv('dh5a_growth_analysis.csv', sep='\t')

In [14]:
fn = '201208_hme63_growth_curve.csv'
df, g = readPlates(fn)
display(df)
print(g)

,t,C17.0,C17.1,C17.2,C18.3,C18.4,C18.5,C5.6,C5.7,C5.8,...,S6.98,S13.99,S13.100,S13.101,S7.102,S7.103,S7.104,S9.105,S9.106,S9.107
0,0.0,0.081611,0.080377,0.083273,0.078518,0.083587,0.081075,0.222381,0.211108,0.207782,...,0.097580,0.062737,0.070932,0.088215,0.067400,0.073899,0.092817,0.064582,0.074470,0.089502
1,90.0,0.085673,0.087031,0.088158,0.084012,0.088681,0.089222,0.308402,0.286544,0.280394,...,0.102950,0.062394,0.071266,0.092736,0.068151,0.074612,0.096545,0.064565,0.075535,0.091231
2,180.0,0.104084,0.106115,0.106064,0.105539,0.110155,0.114183,0.436961,0.431597,0.421904,...,0.129917,0.062670,0.073425,0.108513,0.069394,0.081639,0.115847,0.065189,0.081175,0.104520
3,270.0,0.138011,0.139076,0.136594,0.149523,0.151884,0.158468,0.636792,0.654922,0.629049,...,0.177932,0.063140,0.078969,0.139273,0.073462,0.101282,0.157076,0.066235,0.096418,0.129747
4,360.0,0.176875,0.181672,0.175403,0.199704,0.200620,0.216589,0.834348,0.845529,0.777508,...,0.229406,0.064743,0.093908,0.177977,0.086921,0.137717,0.208314,0.068058,0.126323,0.168958
5,1440.0,0.473825,0.481752,0.463851,0.518885,0.510910,0.581956,1.528227,1.479317,1.474588,...,0.459599,0.440759,0.448918,0.500818,0.479310,0.510905,0.520591,0.492681,0.491876,0.518110

{'C17': ['C17.0', 'C17.1', 'C17.2'], 'C18': ['C18.3', 'C18.4', 'C18.5'], 'C5': ['C5.6', 'C5.7', 'C5.8'], 'C6': ['C6.9', 'C6.10', 'C6.11'], 'C16': ['C16.12', 'C16.13', 'C16.14'], 'C13': ['C13.15', 'C13.16', 'C13.17'], 'C8': ['C8.18', 'C8.19', 'C8.20'], 'C7': ['C7.21', 'C7.22', 'C7.23'], 'C12': ['C12.24', 'C12.25', 'C12.26'], 'C4': ['C4.27', 'C4.28', 'C4.29'], 'C19': ['C19.30', 'C19.31', 'C19.32'], 'C1': ['C1.33', 'C1.34', 'C1.35'], 'C3': ['C3.36', 'C3.37', 'C3.38'], 'C9': ['C9.39', 'C9.40', 'C9.41'], 'C14': ['C14.42', 'C14.43', 'C14.44'], 'C11': ['C11.45', 'C11.46', 'C11.47'], 'C2': ['C2.48', 'C2.49', 'C2.50'], 'C10': ['C10.51', 'C10.52', 'C10.53'], 'C15': ['C15.54', 'C15.55', 'C15.56'], 'C20': ['C20.57', 'C20.58', 'C20.59'], 'C21': ['C21.60', 'C21.61', 'C21.62'], 'S3': ['S3.63', 'S3.64', 'S3.65'], 'S4': ['S4.66', 'S4.67', 'S4.68'], 'S2': ['S2.69', 'S2.70', 'S2.71'], 'S14': ['S14.72', 'S14.73', 'S14.74'], 'S10': ['S10.75', 'S10.76', 'S10.77'], 'S5': ['S5.78', 'S5.79', 'S5.80'], 'S12': ['S12.81', 'S12.82', 'S12.83'], 'S8': ['S8.84', 'S8.85', 'S8.86'], 'S1': ['S1.87', 'S1.88', 'S1.89'], 'S11': ['S11.90', 'S11.91', 'S11.92'], 'S15': ['S15.93', 'S15.94', 'S15.95'], 'S6': ['S6.96', 'S6.97', 'S6.98'], 'S13': ['S13.99', 'S13.100', 'S13.101'], 'S7': ['S7.102', 'S7.103', 'S7.104'], 'S9': ['S9.105', 'S9.106', 'S9.107']}

In [16]:
h = growthAnalysis(df, g, 'hme63')

C17
C18
C5
C6
C16
C13
C8
C7
C12
C4
C19
C1
C3
C9
C14
C11
C2
C10
C15
C20
C21
S3
S4
S2
S14
S10
S5
S12
S8
S1
S11
S15
S6
S13
S7
S9

In [17]:
h

,sample,growth plateau min,growth plateau max,mean growth plateau,std growth plateau,min peak growth rate t,max peak growth rate t,mean peak growth rate t,std peak growth rate t,min shortest doubling time,max shortest doubling time,mean shortest doubling time,std shortest doubling time
0,C17,0.462103,0.485750,0.473732,0.009658,257.575758,318.181818,292.929293,2.575262e+01,150.506395,216.916749,178.721987,28.015135
1,C18,0.512025,0.581507,0.537420,0.031294,272.727273,272.727273,272.727273,0.000000e+00,150.038050,178.155665,162.172763,11.797075
2,C5,1.484298,1.538158,1.503008,0.024872,106.060606,121.212121,116.161616,7.142493e+00,128.436090,142.681927,135.618465,5.816446
3,C6,1.566039,1.617243,1.595873,0.021744,151.515152,196.969697,171.717172,1.889726e+01,176.344643,188.709410,182.004402,5.101717
4,C16,1.522115,1.577366,1.541803,0.025195,318.181818,378.787879,348.484848,2.474232e+01,193.134916,219.086140,209.716544,11.758020
5,C13,1.327689,1.442900,1.375653,0.048971,257.575758,318.181818,282.828283,2.575262e+01,168.288542,203.220092,182.805462,14.858006
6,C8,0.583669,0.602899,0.590615,0.008711,393.939394,393.939394,393.939394,0.000000e+00,52.304237,55.913542,54.155353,1.474957
7,C7,0.287110,0.307155,0.295323,0.008574,424.242424,424.242424,424.242424,0.000000e+00,47.272244,52.873615,49.874156,2.303964
8,C12,0.500055,0.514914,0.505883,0.006475,424.242424,424.242424,424.242424,0.000000e+00,35.534567,43.129777,38.831521,3.180540
9,C4,0.501763,0.544722,0.518267,0.018897,409.090909,409.090909,409.090909,5.684342e-14,42.029549,48.631204,45.233884,2.698567
10,C19,0.498339,0.551981,0.523207,0.022073,272.727273,303.030303,287.878788,1.237116e+01,151.895717,162.544118,158.193837,4.560166
11,C1,1.463907,1.506682,1.483193,0.017714,136.363636,181.818182,156.565657,1.889726e+01,114.800478,128.246774,122.297978,5.597593
12,C3,0.339922,0.374347,0.361065,0.015114,424.242424,424.242424,424.242424,0.000000e+00,41.824080,46.039191,44.103312,1.737855
13,C9,1.282875,1.325022,1.298270,0.018989,212.121212,272.727273,247.474747,2.575262e+01,186.625178,193.605298,190.582347,2.925189
14,C14,1.262671,1.471144,1.364242,0.085192,212.121212,242.424242,222.222222,1.428499e+01,215.229979,222.968492,220.233519,3.543157
15,C11,0.290158,0.358907,0.318081,0.029512,424.242424,424.242424,424.242424,0.000000e+00,37.410871,45.906880,40.841993,3.655811
16,C2,1.522600,1.602118,1.564661,0.032626,45.454545,60.606061,55.555556,7.142493e+00,135.944186,143.574807,140.474562,3.275215
17,C10,1.443054,1.543512,1.476743,0.047214,242.424242,272.727273,262.626263,1.428499e+01,200.754487,212.263627,206.984139,4.746380
18,C15,0.416362,0.505240,0.453586,0.037692,409.090909,424.242424,414.141414,7.142493e+00,31.658293,39.414056,36.006868,3.235493
19,C20,0.487063,0.507026,0.498246,0.008325,181.818182,393.939394,323.232323,9.999490e+01,55.312726,185.325330,101.339997,59.477896
20,C21,0.491692,0.556415,0.525686,0.026524,166.666667,393.939394,318.181818,1.071374e+02,49.751513,196.967270,103.383694,66.408861
21,S3,0.545319,0.688965,0.614103,0.058801,106.060606,272.727273,186.868687,6.813504e+01,139.602162,153.372824,145.812821,5.702241
22,S4,0.076411,0.335319,0.214015,0.106326,151.515152,424.242424,333.333333,1.285649e+02,52.151871,2224.553254,777.567232,1023.174832
23,S2,0.408747,0.481092,0.443116,0.029644,409.090909,424.242424,419.191919,7.142493e+00,32.799175,47.502282,39.031519,6.207696
24,S14,0.495681,0.499259,0.497937,0.001603,227.272727,272.727273,257.575758,2.142748e+01,160.964194,202.023104,176.578509,18.146337
25,S10,0.441753,0.484441,0.466274,0.017997,151.515152,409.090909,313.131313,1.149475e+02,45.464879,182.680913,101.459073,58.789940
26,S5,0.285279,0.516068,0.394166,0.094668,409.090909,424.242424,419.191919,7.142493e+00,40.021073,55.484735,50.295935,7.265546
27,S12,0.475321,0.491680,0.485171,0.007084,393.939394,409.090909,404.040404,7.142493e+00,42.297440,68.941937,55.789914,10.880234
28,S8,0.409722,0.473428,0.442584,0.026047,409.090909,424.242424,414.141414,7.142493e+00,38.086194,65.824747,49.509972,11.840558
29,S1,1.479395,1.496602,1.490652,0.007964,257.575758,287.878788,272.727273,1.237116e+01,236.989738,248.367209,243.726609,4.875618
30,S11,0.425955,0.471836,0.454779,0.020495,333.333333,424.242424,388.888889,3.976772e+01,37.172491,206.063037,99.074219,75.963317
31,S15,0.436307,0.492980,0.466933,0.023362,363.636364,424.242424,404.040404,2.856997e+01,34.101598,110.683201,59.999911,35.841380
32,S6,0.460441,0.467080,0.464479,0.002895,227.272727,409.090909,343.434343,8.237124e+01,44.207364,196.511672,103.914809,66.384918
33,S13,0.440731,0.499416,0.463014,0.025955,333.333333,424.242424,388.888889,3.976772e+01,34.613929,141.756030,76.882839,46.569465
34,S7,0.479293,0.523058,0.504292,0.018403,272.727273,409.090909,353.535354,5.846382e+01,47.097232,197.672163,107.943755,64.775638
35,S9,0.491658,0.517135,0.500492,0.011776,363.636364,424.242424,393.939394,2.474232e+01,29.465045,104.650928,69.253521,30.851152

In [19]:
h.to_csv('hme63_growth_analysis.csv', sep='\t')